server:
  port: 9192
  servlet:
    context-path: /product-service

logging:
  level:
    org:
      springframework: INFO
      hibernate:
        id: DEBUG
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
    com:
      products: DEBUG
  pattern:
    console: '"%d{yyyy-MM-dd HH:mm:ss} -%msg%n'

spring:
  jpa:
    properties:
      hibernate:
        id:
          new_generator_mappings: false
    hibernate:
      ddl-auto: none
  datasource:
    hikari:
      connectionTimeout: '20000'
      maximumPoolSize: '5'
  redis:
    host: localhost
    port: 6379
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

authorize:
  excluded:
    urls:
      list: GET:/lezdl/roleurl,GET:/lezdl/roleurl/all,GET:/lezdl/roleurl/appconfig
      list-patterns: GET:/lezdl/roleurl/appconfig/[0-9]* ,GET:/lezdl/user/config/[0-9]*


jdbc:
  driverClassName: com.mysql.jdbc.Driver
  url : jdbc:mysql://localhost:3306/b2b_db
  username: root
  password: root

hibernate:
  dialect: org.hibernate.dialect.MySQL8Dialect
  hbm2ddl:
    auto: none

jwt:
  roleid:
    key: roleid
  rolename:
    key: rolename
  vendorid:
    key: vendorid
  userid:
    key: userId
  mobile:
    key: mobile
  rolecode:
    key: roleCode